[package]
name = "chat_backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.5.12"
jwt-simple = "0.11.0"
redis = { version = "0.21.5", features = [ "tokio-native-tls-comp"] }
sqlx = { version = "0.6.0", features = ["runtime-tokio-rustls", "postgres"] }
